### ISSUE TITLE
[ERROR] Can't install cffi==1.14.0

### ISSUE THREAD

**Issue by TheOppaiDragon** [rehmatworks/gplaydl#38]
```
D:\Downloader APK\gplaydl>pip install --upgrade --force-reinstall gplaydl==1.3.5
Collecting gplaydl==1.3.5
  Using cached gplaydl-1.3.5.tar.gz (3.8 kB)
  Preparing metadata (setup.py) ... done
Collecting certifi==2020.4.5.1 (from gplaydl==1.3.5)
  Using cached certifi-2020.4.5.1-py2.py3-none-any.whl (157 kB)
Collecting cffi==1.14.0 (from gplaydl==1.3.5)
  Using cached cffi-1.14.0.tar.gz (463 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\fazep\AppData\Local\Temp\pip-install-gnytea0a\cffi_16a75588f9684082a4d873fd6b4ae30e\setup.py", line 127, in <module>
          if sys.platform == 'win32' and uses_msvc():
        File "C:\Users\fazep\AppData\Local\Temp\pip-install-gnytea0a\cffi_16a75588f9684082a4d873fd6b4ae30e\setup.py", line 105, in uses_msvc
          return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
        File "C:\Python310\lib\distutils\command\config.py", line 225, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "C:\Python310\lib\distutils\command\config.py", line 132, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "C:\Python310\lib\distutils\_msvccompiler.py", line 323, in compile
          self.initialize()
        File "C:\Python310\lib\distutils\_msvccompiler.py", line 220, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Python310\lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Python310\lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by TheOppaiDragon** [comment]
> https://github.com/3052/google

what i need to do?

**Comment by meltingscales** [comment]
Getting the same error on Ubuntu 22.04.3 LTS. Would love to see this fixed. Anyone have any ideas?
